# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    wget -q https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
    unzip terraform_0.15.0_linux_amd64.zip -d $(Agent.ToolsDirectory)/terraform
    rm terraform_0.15.0_linux_amd64.zip
    echo "##vso[task.prependpath]$(Agent.ToolsDirectory)/terraform"
  displayName: 'Install Terraform'

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'